apiVersion: v1
kind: PersistentVolume
metadata:
  name: mimic-iv-pv
spec:
  storageClassName: "premium-rwo"
  capacity:
    storage: 20G
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: mimic-iv-pvc
    namespace: jhub
  gcePersistentDisk:
    pdName: mimic-iv
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mimic-iv-pvc
  namespace: jhub
spec:
  storageClassName: "premium-rwo"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
