apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mimic-iv-pvc-tmp
  namespace: jhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
  storageClassName: premium-rwo
