apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  namespace: jhub
spec:
  volumes:
    - name: mimic-iv-storage
      persistentVolumeClaim:
        claimName: mimic-iv-pvc
    - name: mimic-iv-storage-tmp
      persistentVolumeClaim:
        claimName: mimic-iv-pvc-tmp
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 9999
          name: "http-server"
      volumeMounts:
        - mountPath: "/data"
          name: mimic-iv-storage
        - mountPath: "/data2"
          name: mimic-iv-storage-tmp
